# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: "wiki:"

lecard_short:
  _target_: dpr.data.retriever_data.JsonLawCtxSrc
  query_ridx_path: "/mnt/d/github/THU_PASS/year3/Information_Retreival/Assignments/data/data/documents"
  id_prefix: "" #'lecard:'
