# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

lecard_short:
  _target_: dpr.data.retriever_data.JsonLawCtxSrc
  query_ridx_path:
  id_prefix: 'lecard:'